### PR TITLE
Add in fonts for weasyprint / Upgrade Weasyprint to 52.3

### PR DESCRIPTION
**Pull request by seeker25**
Add in fonts for weasyprint. As requested by Jack. 

Example developer usage after this has been merged:

body {
font-family: 'BC Sans Regular';
}

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
Would you be able to get rid of the empty file references from the commit history please.

**Comment by WadeBarnes** [comment]
Would it also be wort upgrading to the most recent version of WeasyPrint; v52.3?

**Comment by seeker25** [comment]
Well this is frustrating, sometimes I see Binary File, then it flips back to empty

**Comment by WadeBarnes** [comment]
> Well this is frustrating, sometimes I see Binary File, then it flips back to empty

Are those new (added) files?

**Comment by seeker25** [comment]
> > Well this is frustrating, sometimes I see Binary File, then it flips back to empty
> 
> Are those new (added) files?

Yes, and it seems to be a common problem across github.

**Comment by WadeBarnes** [comment]
Ok, no problem in that case.

**Pull request merged**
